# This file was generated by GoReleaser. DO NOT EDIT.
class Bigip < Formula
  desc ""
  homepage ""
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stobias123/bigip-cli/releases/download/v0.0.5/bigip-cli_0.0.5_macOS_amd64.zip"
    sha256 "1a6f4510d6d7e2fb720bf2ca15511e353af1e6ef0aa94ff98ec91dd865e37b61"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stobias123/bigip-cli/releases/download/v0.0.5/bigip-cli_0.0.5_linux_amd64.zip"
    sha256 "a52dac48b63559da5295361a03f72ada9223c9beb6c0edcc8ede46578dda8a3f"
  end

  def install
    bin.install "bigip"
  end
end
